### ISSUE TITLE
Video Quality

### ISSUE THREAD

**Issue by bwatson78** [learn-co-curriculum/oo-ruby-video-review-object-models#1]
The video quality in this review is not clear enough to see everything typed.

**Comment by kkterai** [comment]
I can't open this video, "Overview of object models," using the links provided. Is there another I can use?

**Comment by curiositypaths** [comment]
Hi there,

The YouTube videos appear to work now and both videos are available in 1080p resolution. It's possible that YouTube is lowering the default play resolution if your network is running slow.

If you are still unable to view the videos feel free to reopen the issue.

As always, thanks for contributing! 💙
